import type { HassEntity, HomeAssistant } from "./types/home-assistant";

export type PanelLanguage = "en" | "uk";

const EN_TRANSLATIONS = {
  "app.title": "DahuaBridge Surveillance",
  "app.subtitle": "Full-panel command center",
  "state.online": "Online",
  "state.offline": "Offline",
  "state.healthy": "Healthy",
  "state.attention": "Attention",
  "state.recording": "Recording",
  "state.standby": "Standby",
  "state.connected": "Connected",
  "state.unavailable": "Unavailable",
  "state.armed": "Armed",
  "state.sensorOff": "Sensor Off",
  "state.unknown": "Unknown",
  "state.writable": "Writable",
  "state.blocked": "Blocked",
  "state.active": "Active",
  "state.idle": "Idle",
  "state.ringing": "Ringing",
  "state.activeCall": "Active Call",
  "state.recordingActive": "Recording active",
  "state.recordingIdle": "Recording idle",
  "metric.camerasOnline": "Cameras Online",
  "metric.events24h": "Events 24H",
  "metric.motion": "Motion",
  "metric.human": "Human",
  "metric.vehicle": "Vehicle",
  "metric.ivs": "IVS",
  "metric.nvrHealth": "NVR Health",
  "metric.focus": "Focus",
  "metric.doorStation": "Door Station",
  "metric.view": "View",
  "kind.ipcCamera": "IPC Camera",
  "kind.nvrChannel": "NVR Channel",
  "kind.doorStation": "Door Station",
  "kind.overview": "Overview",
  "unit.room": "room",
  "unit.rooms": "rooms",
  "unit.drive": "drive",
  "unit.drives": "drives",
  "unit.channel": "channel",
  "unit.channels": "channels",
  "unit.alert": "alert",
  "unit.alerts": "alerts",
  "unit.lock": "lock",
  "unit.locks": "locks",
  "unit.alarm": "alarm",
  "unit.alarms": "alarms",
  "unit.exportTarget": "export target",
  "unit.exportTargets": "export targets",
  "unit.forwardError": "forward error",
  "unit.forwardErrors": "forward errors",
  "storage.used": "{value} used",
  "storage.total": "{value} total",
  "storage.percentUsed": "{value}% used",
  "storage.driveCount": "{count} {unit}",
  "storage.summaryUsed": "{used} / {total} used",
  "storage.summaryUsedPercent": "{used} / {total} used ({percent}%)",
  "storage.unknown": "Storage unknown",
  "storage.usageUnknown": "Usage unknown",
  "header.returnOverview": "Return to overview",
  "header.overviewSelected": "Overview selected",
  "header.hideSidebar": "Hide sidebar",
  "header.showSidebar": "Show sidebar",
  "header.hideInspector": "Hide inspector",
  "header.showInspector": "Show inspector",
  "sidebar.search": "Search devices",
  "sidebar.filter.all": "All",
  "sidebar.filter.alerts": "Alerts",
  "sidebar.filter.nvr": "NVR",
  "sidebar.filter.vto": "VTO",
  "sidebar.doorStations": "Door Stations",
  "sidebar.nvrSystems": "NVR Systems",
  "sidebar.ipcCameras": "IPC Cameras",
  "sidebar.nvrStorage": "NVR Storage",
  "sidebar.noStorage": "No NVR storage state discovered.",
  "sidebar.unassigned": "Unassigned",
  "tab.overview": "Overview",
  "tab.events": "Events",
  "tab.recordings": "Recordings",
  "tab.mp4": "MP4",
  "tab.settings": "Settings",
  "button.snapshot": "Snapshot",
  "button.startMp4": "Start MP4",
  "button.stopMp4": "Stop MP4",
  "button.returnLive": "Return Live",
  "button.download": "Download",
  "button.export": "Export",
  "button.play": "Play",
  "button.playing": "Playing",
  "button.ptzControls": "PTZ Controls",
  "button.closePtz": "Close PTZ",
  "button.zoomIn": "Zoom +",
  "button.zoomOut": "Zoom -",
  "button.focusFar": "Focus +",
  "button.focusNear": "Focus -",
  "button.lightSmart": "Return to Smart Light",
  "button.lightWhite": "Turn on White Light",
  "button.warningLightOff": "Turn Warning Light Off",
  "button.warningLightOn": "Turn Warning Light On",
  "button.sirenOff": "Turn Siren Off",
  "button.sirenOn": "Turn Siren On",
  "button.enableStreamAudio": "Enable Stream Audio",
  "button.disableStreamAudio": "Disable Stream Audio",
  "button.streamVolume": "Stream Volume",
  "button.playStream": "Play Stream",
  "button.stopStream": "Stop Stream",
  "button.enableMic": "Enable Mic",
  "button.disableMic": "Disable Mic",
  "button.unlock": "Unlock",
  "button.unlockTarget": "Unlock {target}",
  "button.answerCall": "Answer Call",
  "button.hangUp": "Hang Up",
  "button.autoRecordOn": "Auto Record On",
  "button.autoRecordOff": "Auto Record Off",
  "button.enableExternalUplink": "Enable External Uplink",
  "button.disableExternalUplink": "Disable External Uplink",
  "button.resetBridgeSession": "Reset Bridge Session",
  "panel.noDevicesTitle": "No devices discovered",
  "panel.noDevicesBody": "The card did not find any DahuaBridge camera entities in Home Assistant.",
  "panel.noDevicesHint": "Check that the integration entities exist and reload the DahuaBridge config entry so the latest bridge metadata is exposed to the frontend.",
  "panel.configMissing": "Card configuration missing.",
  "panel.hassMissing": "Home Assistant state unavailable.",
  "panel.deviceNotFound": "Device {deviceId} was not found in DahuaBridge camera discovery.",
  "editor.general": "General",
  "editor.discovery": "Discovery",
  "editor.title": "Title",
  "editor.subtitle": "Subtitle",
  "editor.browserBridgeUrl": "Browser Bridge URL",
  "editor.lookbackHours": "Lookback Hours",
  "editor.pollSeconds": "Poll Seconds",
  "editor.visibleEvents": "Visible Events",
  "editor.preferredVto": "Preferred VTO",
  "editor.discoveryHint": "The card discovers DahuaBridge VTOs, NVR channels, rooms, sensors, and event surfaces from Home Assistant and the bridge-native camera metadata. Room grouping follows the HA area assigned to each channel device.",
  "editor.browserBridgeHint": "Set Browser Bridge URL when the browser reaches the bridge through a public hostname instead of the bridge's internal public base URL.",
  "media.streamEntityUnavailable": "Stream entity unavailable.",
  "media.archiveStreamUnavailable": "Archive stream unavailable.",
  "media.streamUnavailable": "Stream unavailable.",
  "view.live": "Live",
  "view.playback": "Playback",
  "badge.nvrRecording": "NVR Recording",
  "badge.mp4Clip": "MP4 Clip",
  "badge.streamDown": "Stream Down",
  "badge.micCodec": "Mic {codec}",
  "badge.speaker": "Speaker",
  "badge.doorbell": "Doorbell",
  "badge.tamper": "Tamper",
  "badge.access": "Access",
  "ptz.adjusting": "Adjusting",
  "archive.seek": "Archive seek",
  "archive.seekDate": "Seek date",
  "archive.date": "Date",
  "archive.eventType": "SMD/IVS type",
  "archive.selectedDate": "Selected date",
  "archive.start": "Start",
  "archive.end": "End",
  "archive.loadingEvents": "Loading SMD/IVS.",
  "archive.loadingChunks": "Loading recording chunks.",
  "archive.loadingMp4": "Loading MP4 clips.",
  "archive.noEventsForDate": "No SMD/IVS found for {date}.",
  "archive.noChunksForDate": "No recording chunks found for {date}.",
  "archive.noMp4ForDate": "No MP4 clips found for {date}.",
  "archive.previous": "Previous",
  "archive.next": "Next",
  "archive.noEventUrl": "SMD/IVS archive URL is unavailable for this camera.",
  "archive.noChunkUrl": "Recording chunk archive URL is unavailable for this camera.",
  "archive.channelLabel": "Archive Channel {channel}",
  "archive.event.all": "All SMD/IVS",
  "archive.event.human": "Human",
  "archive.event.vehicle": "Vehicle",
  "archive.event.animal": "Animal",
  "archive.event.crossLine": "Cross Line",
  "archive.event.crossRegion": "Cross Region",
  "events.recentTitle": "Recent Events",
  "events.historyTitle": "Event History",
  "events.syncing": "Syncing",
  "events.degraded": "Bridge sync degraded",
  "events.shown": "{filtered}/{total} shown",
  "events.recent": "Recent",
  "events.history": "History",
  "events.bufferedHistory": "Buffered history",
  "events.type": "Event type",
  "events.resetFilters": "Reset filters",
  "events.noneForFilters": "No events match the current filters.",
  "events.noneRecent": "No recent events.",
  "events.activeNow": "Active now",
  "events.recentEvent": "Recent event",
  "events.recovered": "Recovered",
  "events.state": "State",
  "events.cleared": "Cleared",
  "events.start": "Start",
  "events.source": "Source",
  "events.rule": "Rule",
  "events.region": "Region",
  "events.object": "Object",
  "events.channel": "Channel",
  "event.motion": "Motion",
  "event.motionCleared": "Motion Cleared",
  "event.human": "Human",
  "event.humanDetected": "Human Detected",
  "event.humanCleared": "Human Cleared",
  "event.vehicle": "Vehicle",
  "event.vehicleDetected": "Vehicle Detected",
  "event.vehicleCleared": "Vehicle Cleared",
  "event.tripwire": "Tripwire",
  "event.tripwireCleared": "Tripwire Cleared",
  "event.intrusion": "Intrusion",
  "event.intrusionCleared": "Intrusion Cleared",
  "event.doorbell": "Doorbell",
  "event.doorbellPressed": "Doorbell Pressed",
  "event.doorbellCleared": "Doorbell Cleared",
  "event.call": "Call",
  "event.callStarted": "Call Started",
  "event.callEnded": "Call Ended",
  "event.access": "Access",
  "event.accessGranted": "Access Granted",
  "event.accessClosed": "Access Closed",
  "event.alarmTriggered": "Alarm Triggered",
  "event.alarmCleared": "Alarm Cleared",
  "event.tamper": "Tamper",
  "event.tamperDetected": "Tamper Detected",
  "event.tamperCleared": "Tamper Cleared",
  "inspector.streamStatus": "Stream Status",
  "inspector.liveSource": "Preferred live source",
  "inspector.liveSourceCamera": "Camera",
  "inspector.liveSourceDefault": "Use integration default ({source})",
  "inspector.liveSourceEffective": "Currently using {source}",
  "inspector.liveSourceHint": "Use the integration default or choose a preferred source. Live video switches to the other source if it fails. Recorded playback uses the NVR.",
  "inspector.liveSourceUpdateRequired": "Update the bridge to change the live source.",
  "inspector.liveSourceCameraUnavailable": "Direct camera streaming is unavailable; live video uses the NVR when reachable.",
  "error.liveSourceFailed": "Could not change the live source.",
  "inspector.liveReady": "Live stream ready",
  "inspector.liveUnavailable": "Live stream unavailable",
  "inspector.recommended": "Recommended",
  "inspector.recommendedProfile": "Recommended {profile}",
  "inspector.onvifStreamReady": "ONVIF stream ready",
  "inspector.onvifSnapshotReady": "ONVIF snapshot ready",
  "inspector.preferredProfile": "Preferred profile: {profile}",
  "inspector.preferredSource": "Preferred source: {source}",
  "inspector.primaryRouteExposed": "Primary stream route is exposed.",
  "inspector.primaryRouteMissing": "No primary stream route is exposed.",
  "inspector.streamProfiles": "Stream Profiles",
  "inspector.subtype": "Subtype {subtype}",
  "inspector.browserStreamAudio": "Browser Stream Audio",
  "inspector.playerAudioAvailable": "Player audio available",
  "inspector.playerAudioUnavailable": "Player audio unavailable",
  "inspector.bridgeAdapter": "Bridge Adapter",
  "inspector.bridgeBaseAvailable": "Bridge base URL available",
  "inspector.bridgeBaseUnavailable": "Bridge base URL unavailable",
  "inspector.eventRouteAvailable": "Event route available",
  "inspector.eventRouteUnavailable": "Event route unavailable",
  "inspector.bridgeDiagnosticsHint": "Bridge diagnostics are only shown here when a required route is missing.",
  "inspector.recorder": "Recorder",
  "inspector.connection": "Connection",
  "inspector.storage": "Storage",
  "inspector.configWrites": "Config Writes",
  "inspector.channelsRecording": "Channels recording",
  "inspector.alerts": "Alerts",
  "inspector.driveInventory": "Drive Inventory",
  "inspector.noDrives": "No drive child devices discovered for this recorder.",
  "inspector.recordingControls": "Recording Controls",
  "inspector.intercomControls": "Intercom Controls",
  "inspector.sessionResetReady": "Session reset ready",
  "inspector.sessionResetUnavailable": "Session reset unavailable",
  "inspector.bridgeUplinkSupported": "Bridge uplink supported",
  "inspector.bridgeUplinkUnavailable": "Bridge uplink unavailable",
  "inspector.bridgeOutputSupported": "Bridge output supported",
  "inspector.bridgeOutputUnavailable": "Bridge output unavailable",
  "vto.doorStationSuffix": "{room} door station",
  "vto.status": "Door Station Status",
  "vto.lockTargets": "Lock Targets",
  "vto.lockTarget": "Lock Target",
  "vto.intercomBridge": "Intercom Bridge",
  "vto.sessionActive": "Session Active",
  "vto.sessions": "Sessions {count}",
  "vto.codecUnknown": "Codec unknown",
  "vto.browserMicReady": "Browser mic ready",
  "vto.browserMicUnavailable": "Browser mic unavailable",
  "vto.micInactive": "Mic inactive",
  "vto.micUnavailable": "Mic unavailable",
  "vto.micNegotiating": "Mic negotiating",
  "vto.micConnecting": "Mic connecting",
  "vto.micWaitingBridge": "Waiting for bridge media",
  "vto.micConnected": "Mic connected",
  "vto.micReconnecting": "Mic reconnecting",
  "vto.micReconnectingIn": "Reconnecting mic in {seconds}s",
  "vto.micState": "Mic {state}",
  "vto.externalExportSupported": "External export supported",
  "vto.noExternalExport": "No external export",
  "vto.externalUplinkEnabled": "External uplink enabled",
  "vto.externalUplinkDisabled": "External uplink disabled",
  "vto.bridgeUplinkActive": "Bridge uplink active",
  "vto.bridgeUplinkIdle": "Bridge uplink idle",
  "vto.source": "Source: {value}",
  "vto.started": "Started: {value}",
  "vto.duration": "Duration: {value}",
  "vto.model": "Model: {value}",
  "vto.hold": "Hold: {value}",
  "vto.holdCompact": "Hold {value}",
  "profile.quality": "Quality (Main Stream)",
  "profile.stable": "Stable (Substream)",
  "profile.unknown": "unknown",
  "source.nativeHa": "Native HA",
  "source.nativeHaRtsp": "Home Assistant / Bridge RTSP",
  "source.bridgeDash": "Bridge DASH",
  "source.bridgeHls": "Bridge HLS (H.264/AAC)",
  "source.bridgeWebRtc": "Bridge WebRTC",
  "source.bridgeMjpeg": "Bridge MJPEG",
  "source.auto": "Auto (Bridge Recommended)",
  "source.dash": "DASH",
  "source.hls": "HLS",
  "source.mjpeg": "MJPEG",
  "error.bridgeMp4VtoUnavailable": "Bridge MP4 recording is unavailable for this VTO.",
  "error.vtoBridgeRecordingFailed": "VTO bridge recording request failed.",
  "error.smdPlaybackUnavailable": "SMD/IVS MP4 playback is unavailable for this row.",
  "error.playbackSourceUnavailable": "Playback is unavailable for the selected archive source.",
  "error.archiveExportNoPlayback": "Bridge archive export completed without a playback URL.",
  "error.archivePlaybackExportFailed": "Bridge archive playback export failed.",
  "error.archiveRequestFailed": "Archive recording request failed.",
  "error.bridgeMp4RequestFailed": "Bridge MP4 request failed.",
  "error.archiveExportNoDownload": "Bridge archive export completed without a download URL.",
  "error.archiveExportFailed": "Bridge archive export request failed.",
  "error.historicalUrlUnavailable": "Historical archive proxy URL could not be built for this camera.",
  "error.historicalEventInvalid": "Historical archive event timeframe is invalid.",
  "error.historicalEventProxyUnavailable": "Historical archive event proxy URL could not be built.",
  "error.intercomOfferUnavailable": "Bridge intercom offer URL is unavailable for the selected VTO.",
  "error.browserMicSetupFailed": "Browser microphone setup failed.",
  "error.browserMicCaptureUnavailable": "Browser microphone capture is not available in this browser.",
  "error.controlUnavailable": "Control is unavailable in Home Assistant and no bridge fallback URL was provided.",
  "error.switchControlUnavailable": "Switch control is unavailable in Home Assistant and no bridge fallback URL was provided.",
  "error.ptzUrlUnavailable": "PTZ target URL is unavailable. The card needs bridge-derived camera attributes for direct PTZ control.",
  "error.auxUrlUnavailable": "Aux output URL is unavailable. The bridge base URL could not be derived from the camera entity.",
  "error.auxActionUnavailable": "No compatible deterrence action is available for that output.",
  "error.noActiveMp4Stop": "No active bridge MP4 clip is available to stop for this camera.",
  "error.cameraMp4Unavailable": "Bridge MP4 recording is unavailable for this camera.",
  "error.unexpectedActionFailure": "Unexpected action failure.",
  "error.cardConfigInvalid": "Card configuration is invalid.",
} as const;

export type TranslationKey = keyof typeof EN_TRANSLATIONS;
export type TranslationParams = Record<string, string | number | boolean | null | undefined>;
export type Localizer = (key: TranslationKey, params?: TranslationParams) => string;

const UK_TRANSLATIONS: Record<TranslationKey, string> = {
  "app.title": "Відеонагляд DahuaBridge",
  "app.subtitle": "Повна панель керування",
  "state.online": "Онлайн",
  "state.offline": "Офлайн",
  "state.healthy": "Справно",
  "state.attention": "Увага",
  "state.recording": "Запис",
  "state.standby": "Очікування",
  "state.connected": "Підключено",
  "state.unavailable": "Недоступно",
  "state.armed": "Увімкнено",
  "state.sensorOff": "Сенсор вимкнено",
  "state.unknown": "Невідомо",
  "state.writable": "Доступно для запису",
  "state.blocked": "Заблоковано",
  "state.active": "Активно",
  "state.idle": "Очікування",
  "state.ringing": "Дзвінок",
  "state.activeCall": "Активний виклик",
  "state.recordingActive": "Запис активний",
  "state.recordingIdle": "Запис неактивний",
  "metric.camerasOnline": "Камери онлайн",
  "metric.events24h": "Події 24 год",
  "metric.motion": "Рух",
  "metric.human": "Людина",
  "metric.vehicle": "Авто",
  "metric.ivs": "IVS",
  "metric.nvrHealth": "Стан NVR",
  "metric.focus": "Фокус",
  "metric.doorStation": "Виклична панель",
  "metric.view": "Вигляд",
  "kind.ipcCamera": "IPC камера",
  "kind.nvrChannel": "Канал NVR",
  "kind.doorStation": "Виклична панель",
  "kind.overview": "Огляд",
  "unit.room": "кімната",
  "unit.rooms": "кімнат",
  "unit.drive": "диск",
  "unit.drives": "дисків",
  "unit.channel": "канал",
  "unit.channels": "каналів",
  "unit.alert": "тривога",
  "unit.alerts": "тривог",
  "unit.lock": "замок",
  "unit.locks": "замків",
  "unit.alarm": "сигналізація",
  "unit.alarms": "сигналізацій",
  "unit.exportTarget": "ціль експорту",
  "unit.exportTargets": "цілей експорту",
  "unit.forwardError": "помилка пересилання",
  "unit.forwardErrors": "помилок пересилання",
  "storage.used": "використано {value}",
  "storage.total": "усього {value}",
  "storage.percentUsed": "використано {value}%",
  "storage.driveCount": "{count} {unit}",
  "storage.summaryUsed": "{used} / {total} використано",
  "storage.summaryUsedPercent": "{used} / {total} використано ({percent}%)",
  "storage.unknown": "Стан сховища невідомий",
  "storage.usageUnknown": "Використання невідоме",
  "header.returnOverview": "Повернутися до огляду",
  "header.overviewSelected": "Огляд вибрано",
  "header.hideSidebar": "Сховати бічну панель",
  "header.showSidebar": "Показати бічну панель",
  "header.hideInspector": "Сховати інспектор",
  "header.showInspector": "Показати інспектор",
  "sidebar.search": "Пошук пристроїв",
  "sidebar.filter.all": "Усі",
  "sidebar.filter.alerts": "Тривоги",
  "sidebar.filter.nvr": "NVR",
  "sidebar.filter.vto": "VTO",
  "sidebar.doorStations": "Викличні панелі",
  "sidebar.nvrSystems": "Системи NVR",
  "sidebar.ipcCameras": "IPC камери",
  "sidebar.nvrStorage": "Сховище NVR",
  "sidebar.noStorage": "Стан сховища NVR не знайдено.",
  "sidebar.unassigned": "Не призначено",
  "tab.overview": "Огляд",
  "tab.events": "Події",
  "tab.recordings": "Записи",
  "tab.mp4": "MP4",
  "tab.settings": "Налаштування",
  "button.snapshot": "Знімок",
  "button.startMp4": "Почати MP4",
  "button.stopMp4": "Зупинити MP4",
  "button.returnLive": "До live",
  "button.download": "Завантажити",
  "button.export": "mp4",
  "button.play": "Відтворити",
  "button.playing": "Відтворюється",
  "button.ptzControls": "Керування PTZ",
  "button.closePtz": "Закрити PTZ",
  "button.zoomIn": "Зум +",
  "button.zoomOut": "Зум -",
  "button.focusFar": "Фокус +",
  "button.focusNear": "Фокус -",
  "button.lightSmart": "Повернути розумне світло",
  "button.lightWhite": "Увімкнути біле світло",
  "button.warningLightOff": "Вимкнути сигнальне світло",
  "button.warningLightOn": "Увімкнути сигнальне світло",
  "button.sirenOff": "Вимкнути сирену",
  "button.sirenOn": "Увімкнути сирену",
  "button.enableStreamAudio": "Увімкнути звук потоку",
  "button.disableStreamAudio": "Вимкнути звук потоку",
  "button.streamVolume": "Гучність потоку",
  "button.playStream": "Запустити потік",
  "button.stopStream": "Зупинити потік",
  "button.enableMic": "Увімкнути мікрофон",
  "button.disableMic": "Вимкнути мікрофон",
  "button.unlock": "Відкрити",
  "button.unlockTarget": "Відкрити {target}",
  "button.answerCall": "Відповісти",
  "button.hangUp": "Завершити",
  "button.autoRecordOn": "Автозапис увімкнено",
  "button.autoRecordOff": "Автозапис вимкнено",
  "button.enableExternalUplink": "Увімкнути зовнішній uplink",
  "button.disableExternalUplink": "Вимкнути зовнішній uplink",
  "button.resetBridgeSession": "Скинути сесію Bridge",
  "panel.noDevicesTitle": "Пристрої не знайдено",
  "panel.noDevicesBody": "Картка не знайшла камер DahuaBridge у Home Assistant.",
  "panel.noDevicesHint": "Перевірте, що сутності інтеграції існують, і перезавантажте config entry DahuaBridge, щоб останні метадані bridge були доступні фронтенду.",
  "panel.configMissing": "Конфігурація картки відсутня.",
  "panel.hassMissing": "Стан Home Assistant недоступний.",
  "panel.deviceNotFound": "Пристрій {deviceId} не знайдено в DahuaBridge camera discovery.",
  "editor.general": "Загальні",
  "editor.discovery": "Виявлення",
  "editor.title": "Назва",
  "editor.subtitle": "Підзаголовок",
  "editor.browserBridgeUrl": "Browser Bridge URL",
  "editor.lookbackHours": "Години історії",
  "editor.pollSeconds": "Секунди опитування",
  "editor.visibleEvents": "Видимі події",
  "editor.preferredVto": "Бажаний VTO",
  "editor.discoveryHint": "Картка виявляє DahuaBridge VTO, канали NVR, кімнати, сенсори та поверхні подій з Home Assistant і bridge-native метаданих камери. Групування за кімнатами використовує HA area, призначену кожному пристрою каналу.",
  "editor.browserBridgeHint": "Вкажіть Browser Bridge URL, коли браузер відкриває bridge через публічний hostname замість внутрішнього public base URL bridge.",
  "media.streamEntityUnavailable": "Сутність потоку недоступна.",
  "media.archiveStreamUnavailable": "Архівний потік недоступний.",
  "media.streamUnavailable": "Потік недоступний.",
  "view.live": "Live",
  "view.playback": "Відтворення",
  "badge.nvrRecording": "Запис NVR",
  "badge.mp4Clip": "MP4 кліп",
  "badge.streamDown": "Потік недоступний",
  "badge.micCodec": "Мікрофон {codec}",
  "badge.speaker": "Динамік",
  "badge.doorbell": "Дзвінок",
  "badge.tamper": "Тампер",
  "badge.access": "Доступ",
  "ptz.adjusting": "Налаштування",
  "archive.seek": "Пошук в архіві",
  "archive.seekDate": "Дата пошуку",
  "archive.date": "Дата",
  "archive.eventType": "Тип SMD/IVS",
  "archive.selectedDate": "Вибрана дата",
  "archive.start": "Початок",
  "archive.end": "Кінець",
  "archive.loadingEvents": "Завантаження SMD/IVS.",
  "archive.loadingChunks": "Завантаження фрагментів запису.",
  "archive.loadingMp4": "Завантаження MP4 кліпів.",
  "archive.noEventsForDate": "SMD/IVS за {date} не знайдено.",
  "archive.noChunksForDate": "Фрагменти запису за {date} не знайдено.",
  "archive.noMp4ForDate": "MP4 кліпи за {date} не знайдено.",
  "archive.previous": "",
  "archive.next": "",
  "archive.noEventUrl": "URL архіву SMD/IVS недоступний для цієї камери.",
  "archive.noChunkUrl": "URL фрагментів запису недоступний для цієї камери.",
  "archive.channelLabel": "Канал архіву {channel}",
  "archive.event.all": "Усі SMD/IVS",
  "archive.event.human": "Людина",
  "archive.event.vehicle": "Авто",
  "archive.event.animal": "Тварина",
  "archive.event.crossLine": "Перетин лінії",
  "archive.event.crossRegion": "Перетин області",
  "events.recentTitle": "Останні події",
  "events.historyTitle": "Історія подій",
  "events.syncing": "Синхронізація",
  "events.degraded": "Синхронізація Bridge погіршена",
  "events.shown": "показано {filtered}/{total}",
  "events.recent": "Останні",
  "events.history": "Історія",
  "events.bufferedHistory": "Буфер історії",
  "events.type": "Тип події",
  "events.resetFilters": "Скинути фільтри",
  "events.noneForFilters": "Немає подій для поточних фільтрів.",
  "events.noneRecent": "Немає останніх подій.",
  "events.activeNow": "Активно зараз",
  "events.recentEvent": "Остання подія",
  "events.recovered": "Відновлено",
  "events.state": "Стан",
  "events.cleared": "Очищено",
  "events.start": "Початок",
  "events.source": "Джерело",
  "events.rule": "Правило",
  "events.region": "Регіон",
  "events.object": "Об'єкт",
  "events.channel": "Канал",
  "event.motion": "Рух",
  "event.motionCleared": "Рух завершено",
  "event.human": "Людина",
  "event.humanDetected": "Виявлено людину",
  "event.humanCleared": "Людину очищено",
  "event.vehicle": "Авто",
  "event.vehicleDetected": "Виявлено авто",
  "event.vehicleCleared": "Авто очищено",
  "event.tripwire": "Перетин лінії",
  "event.tripwireCleared": "Перетин лінії очищено",
  "event.intrusion": "Вторгнення",
  "event.intrusionCleared": "Вторгнення очищено",
  "event.doorbell": "Дзвінок",
  "event.doorbellPressed": "Дзвінок натиснуто",
  "event.doorbellCleared": "Дзвінок очищено",
  "event.call": "Виклик",
  "event.callStarted": "Виклик почато",
  "event.callEnded": "Виклик завершено",
  "event.access": "Доступ",
  "event.accessGranted": "Доступ дозволено",
  "event.accessClosed": "Доступ закрито",
  "event.alarmTriggered": "Тривогу спрацьовано",
  "event.alarmCleared": "Тривогу очищено",
  "event.tamper": "Тампер",
  "event.tamperDetected": "Тампер виявлено",
  "event.tamperCleared": "Тампер очищено",
  "inspector.streamStatus": "Стан потоку",
  "inspector.liveSource": "Бажане джерело відео наживо",
  "inspector.liveSourceCamera": "Камера",
  "inspector.liveSourceDefault": "За замовчуванням інтеграції ({source})",
  "inspector.liveSourceEffective": "Зараз використовується: {source}",
  "inspector.liveSourceHint": "Використовуйте стандартне або оберіть бажане джерело. Якщо воно недоступне, відео перемикається на інше джерело. Архів відтворюється з NVR.",
  "inspector.liveSourceUpdateRequired": "Оновіть міст, щоб змінювати джерело відео наживо.",
  "inspector.liveSourceCameraUnavailable": "Прямий потік із камери недоступний; відео відтворюється з NVR, коли він доступний.",
  "error.liveSourceFailed": "Не вдалося змінити джерело відео наживо.",
  "inspector.liveReady": "Live потік готовий",
  "inspector.liveUnavailable": "Live потік недоступний",
  "inspector.recommended": "Рекомендовано",
  "inspector.recommendedProfile": "Рекомендовано {profile}",
  "inspector.onvifStreamReady": "ONVIF потік готовий",
  "inspector.onvifSnapshotReady": "ONVIF знімок готовий",
  "inspector.preferredProfile": "Бажаний профіль: {profile}",
  "inspector.preferredSource": "Бажане джерело: {source}",
  "inspector.primaryRouteExposed": "Основний маршрут потоку доступний.",
  "inspector.primaryRouteMissing": "Основний маршрут потоку недоступний.",
  "inspector.streamProfiles": "Профілі потоку",
  "inspector.subtype": "Підтип {subtype}",
  "inspector.browserStreamAudio": "Звук потоку в браузері",
  "inspector.playerAudioAvailable": "Звук плеєра доступний",
  "inspector.playerAudioUnavailable": "Звук плеєра недоступний",
  "inspector.bridgeAdapter": "Адаптер Bridge",
  "inspector.bridgeBaseAvailable": "Base URL Bridge доступний",
  "inspector.bridgeBaseUnavailable": "Base URL Bridge недоступний",
  "inspector.eventRouteAvailable": "Маршрут подій доступний",
  "inspector.eventRouteUnavailable": "Маршрут подій недоступний",
  "inspector.bridgeDiagnosticsHint": "Діагностика Bridge показується тут лише коли потрібний маршрут відсутній.",
  "inspector.recorder": "Рекордер",
  "inspector.connection": "Підключення",
  "inspector.storage": "Сховище",
  "inspector.configWrites": "Запис конфігурації",
  "inspector.channelsRecording": "Канали записують",
  "inspector.alerts": "Тривоги",
  "inspector.driveInventory": "Інвентар дисків",
  "inspector.noDrives": "Дочірні диски для цього рекордера не знайдено.",
  "inspector.recordingControls": "Керування записом",
  "inspector.intercomControls": "Керування інтеркомом",
  "inspector.sessionResetReady": "Скидання сесії готове",
  "inspector.sessionResetUnavailable": "Скидання сесії недоступне",
  "inspector.bridgeUplinkSupported": "Bridge uplink підтримується",
  "inspector.bridgeUplinkUnavailable": "Bridge uplink недоступний",
  "inspector.bridgeOutputSupported": "Bridge output підтримується",
  "inspector.bridgeOutputUnavailable": "Bridge output недоступний",
  "vto.doorStationSuffix": "{room} виклична панель",
  "vto.status": "Стан викличної панелі",
  "vto.lockTargets": "Цілі замків",
  "vto.lockTarget": "Ціль замка",
  "vto.intercomBridge": "Intercom Bridge",
  "vto.sessionActive": "Сесія активна",
  "vto.sessions": "Сесії {count}",
  "vto.codecUnknown": "Кодек невідомий",
  "vto.browserMicReady": "Мікрофон браузера готовий",
  "vto.browserMicUnavailable": "Мікрофон браузера недоступний",
  "vto.micInactive": "Мікрофон неактивний",
  "vto.micUnavailable": "Мікрофон недоступний",
  "vto.micNegotiating": "Узгодження мікрофона",
  "vto.micConnecting": "Підключення мікрофона",
  "vto.micWaitingBridge": "Очікування bridge media",
  "vto.micConnected": "Мікрофон підключено",
  "vto.micReconnecting": "Повторне підключення мікрофона",
  "vto.micReconnectingIn": "Повторне підключення мікрофона через {seconds}с",
  "vto.micState": "Мікрофон: {state}",
  "vto.externalExportSupported": "Зовнішній експорт підтримується",
  "vto.noExternalExport": "Зовнішнього експорту немає",
  "vto.externalUplinkEnabled": "Зовнішній uplink увімкнено",
  "vto.externalUplinkDisabled": "Зовнішній uplink вимкнено",
  "vto.bridgeUplinkActive": "Bridge uplink активний",
  "vto.bridgeUplinkIdle": "Bridge uplink неактивний",
  "vto.source": "Джерело: {value}",
  "vto.started": "Почато: {value}",
  "vto.duration": "Тривалість: {value}",
  "vto.model": "Модель: {value}",
  "vto.hold": "Утримання: {value}",
  "vto.holdCompact": "Утримання {value}",
  "profile.quality": "Якість (основний потік)",
  "profile.stable": "Стабільний (додатковий потік)",
  "profile.unknown": "невідомо",
  "source.nativeHa": "Native HA",
  "source.nativeHaRtsp": "Home Assistant / RTSP мосту",
  "source.bridgeDash": "Bridge DASH",
  "source.bridgeHls": "Bridge HLS (H.264/AAC)",
  "source.bridgeWebRtc": "Bridge WebRTC",
  "source.bridgeMjpeg": "Bridge MJPEG",
  "source.auto": "Авто (рекомендація Bridge)",
  "source.dash": "DASH",
  "source.hls": "HLS",
  "source.mjpeg": "MJPEG",
  "error.bridgeMp4VtoUnavailable": "MP4 запис Bridge недоступний для цього VTO.",
  "error.vtoBridgeRecordingFailed": "Запит MP4 запису VTO через Bridge не вдався.",
  "error.smdPlaybackUnavailable": "Відтворення MP4 для цього рядка SMD/IVS недоступне.",
  "error.playbackSourceUnavailable": "Відтворення недоступне для вибраного джерела архіву.",
  "error.archiveExportNoPlayback": "Експорт архіву Bridge завершено без URL відтворення.",
  "error.archivePlaybackExportFailed": "Експорт архіву Bridge для відтворення не вдався.",
  "error.archiveRequestFailed": "Запит архівних записів не вдався.",
  "error.bridgeMp4RequestFailed": "Запит MP4 Bridge не вдався.",
  "error.archiveExportNoDownload": "Експорт архіву Bridge завершено без URL завантаження.",
  "error.archiveExportFailed": "Запит експорту архіву Bridge не вдався.",
  "error.historicalUrlUnavailable": "Не вдалося побудувати proxy URL історичного архіву для цієї камери.",
  "error.historicalEventInvalid": "Часовий проміжок історичної архівної події некоректний.",
  "error.historicalEventProxyUnavailable": "Не вдалося побудувати proxy URL історичної архівної події.",
  "error.intercomOfferUnavailable": "URL intercom offer Bridge недоступний для вибраного VTO.",
  "error.browserMicSetupFailed": "Налаштування мікрофона браузера не вдалося.",
  "error.browserMicCaptureUnavailable": "Захоплення мікрофона браузера недоступне в цьому браузері.",
  "error.controlUnavailable": "Керування недоступне в Home Assistant, і bridge fallback URL не надано.",
  "error.switchControlUnavailable": "Керування перемикачем недоступне в Home Assistant, і bridge fallback URL не надано.",
  "error.ptzUrlUnavailable": "PTZ target URL недоступний. Картці потрібні bridge-derived атрибути камери для прямого PTZ керування.",
  "error.auxUrlUnavailable": "URL aux output недоступний. Bridge base URL не вдалося отримати з сутності камери.",
  "error.auxActionUnavailable": "Немає сумісної deterrence дії для цього виходу.",
  "error.noActiveMp4Stop": "Немає активного MP4 кліпу Bridge для зупинки на цій камері.",
  "error.cameraMp4Unavailable": "MP4 запис Bridge недоступний для цієї камери.",
  "error.unexpectedActionFailure": "Неочікувана помилка дії.",
  "error.cardConfigInvalid": "Конфігурація картки некоректна.",
};

const TRANSLATIONS: Record<PanelLanguage, Record<TranslationKey, string>> = {
  en: EN_TRANSLATIONS,
  uk: UK_TRANSLATIONS,
};

export function createLocalizer(language: PanelLanguage): Localizer {
  return (key, params = {}) => {
    const template = TRANSLATIONS[language][key] ?? EN_TRANSLATIONS[key] ?? key;
    return template.replace(/\{(\w+)\}/g, (match, name: string) => {
      const value = params[name];
      return value === null || value === undefined ? match : String(value);
    });
  };
}

export function translate(
  language: PanelLanguage,
  key: TranslationKey,
  params?: TranslationParams,
): string {
  return createLocalizer(language)(key, params);
}

export function normalizePanelLanguage(raw: unknown): PanelLanguage | null {
  const value = String(raw ?? "").trim().toLowerCase();
  if (!value) {
    return null;
  }
  if (value === "uk" || value === "ua" || value === "ukr" || value.startsWith("uk-")) {
    return "uk";
  }
  if (value === "en" || value === "eng" || value.startsWith("en-")) {
    return "en";
  }
  if (value.includes("укра")) {
    return "uk";
  }
  if (value.includes("english")) {
    return "en";
  }
  return null;
}

export function resolvePanelLanguage(hass: HomeAssistant): PanelLanguage {
  const integrationLanguage = Object.values(hass.states)
    .map((entity) => languageFromEntity(entity))
    .find((language): language is PanelLanguage => language !== null);
  if (integrationLanguage) {
    return integrationLanguage;
  }

  const hassLike = hass as HomeAssistant & {
    language?: unknown;
    locale?: { language?: unknown };
    config?: { language?: unknown };
  };
  return (
    normalizePanelLanguage(hassLike.language) ??
    normalizePanelLanguage(hassLike.locale?.language) ??
    normalizePanelLanguage(hassLike.config?.language) ??
    "en"
  );
}

export function languageFromEntity(entity: HassEntity): PanelLanguage | null {
  return (
    normalizePanelLanguage(entity.attributes.bridge_integration_language) ??
    normalizePanelLanguage(entity.attributes.integration_language) ??
    null
  );
}

export function pluralUnit(
  count: number,
  singularKey: TranslationKey,
  pluralKey: TranslationKey,
  t: Localizer,
): string {
  return t(Math.abs(count) === 1 ? singularKey : pluralKey);
}
