package ha

import (
	"sort"

	"RCooLeR/DahuaBridge/internal/streams"
	"gopkg.in/yaml.v3"
)

func RenderDashboardCameraPackage(entries []streams.Entry) (string, error) {
	type mjpegCamera struct {
		Platform string `yaml:"platform"`
		Name     string `yaml:"name"`
		MJPEGURL string `yaml:"mjpeg_url"`
	}

	type packageDoc struct {
		Camera []mjpegCamera `yaml:"camera"`
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ID < entries[j].ID
	})

	doc := packageDoc{Camera: make([]mjpegCamera, 0, len(entries))}
	for _, entry := range entries {
		profileName := "stable"
		profile, ok := entry.Profiles[profileName]
		if !ok || profile.LocalMJPEGURL == "" {
			profileName = entry.RecommendedProfile
			if profileName == "" {
				profileName = "substream"
			}
			profile, ok = entry.Profiles[profileName]
		}
		if !ok || profile.LocalMJPEGURL == "" {
			continue
		}
		doc.Camera = append(doc.Camera, mjpegCamera{
			Platform: "mjpeg",
			Name:     entry.Name + " Dashboard",
			MJPEGURL: profile.LocalMJPEGURL,
		})
	}

	body, err := yaml.Marshal(doc)
	if err != nil {
		return "", err
	}
	return "# Generated by DahuaBridge\n# Dashboard package using bridge-served MJPEG streams.\n" + string(body), nil
}
