package ha

import (
	"fmt"
	"sort"

	"RCooLeR/DahuaBridge/internal/dahua"
	"RCooLeR/DahuaBridge/internal/streams"
	"gopkg.in/yaml.v3"
)

func RenderLovelaceDashboard(entries []streams.Entry) (string, error) {
	type lovelaceView struct {
		Title string           `yaml:"title"`
		Path  string           `yaml:"path"`
		Cards []map[string]any `yaml:"cards"`
	}

	type lovelaceDashboard struct {
		Title string         `yaml:"title"`
		Views []lovelaceView `yaml:"views"`
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ID < entries[j].ID
	})

	cameraCards := make([]map[string]any, 0, len(entries))
	intercomCards := make([]map[string]any, 0, len(entries))
	for _, entry := range entries {
		cameraEntityID := defaultEntityIDFor("camera", entry.ID, "camera")
		card := map[string]any{
			"type":         "picture-glance",
			"title":        entry.Name,
			"camera_image": cameraEntityID,
			"camera_view":  "auto",
			"entities":     dashboardEntityIDs(entry),
		}
		cameraCards = append(cameraCards, card)
		if entry.DeviceKind == dahua.DeviceKindVTO {
			intercomCards = append(intercomCards, intercomCard(entry))
		}
	}

	views := []lovelaceView{
		{
			Title: "Cameras",
			Path:  "dahuabridge",
			Cards: cameraCards,
		},
	}
	if len(intercomCards) > 0 {
		views = append(views, lovelaceView{
			Title: "Intercom",
			Path:  "dahuabridge-intercom",
			Cards: intercomCards,
		})
	}

	body, err := yaml.Marshal(lovelaceDashboard{
		Title: "DahuaBridge",
		Views: views,
	})
	if err != nil {
		return "", err
	}

	return "# Generated by DahuaBridge\n# Lovelace dashboard layout using auto-created MQTT snapshot cameras, activity entities, and VTO intercom controls.\n" + string(body), nil
}

func dashboardEntityIDs(entry streams.Entry) []string {
	switch entry.DeviceKind {
	case dahua.DeviceKindNVRChannel, dahua.DeviceKindIPC:
		return []string{
			defaultEntityIDFor("binary_sensor", entry.ID, "motion"),
			defaultEntityIDFor("binary_sensor", entry.ID, "human"),
			defaultEntityIDFor("binary_sensor", entry.ID, "vehicle"),
			defaultEntityIDFor("binary_sensor", entry.ID, "tripwire"),
			defaultEntityIDFor("binary_sensor", entry.ID, "intrusion"),
		}
	case dahua.DeviceKindVTO:
		return []string{
			defaultEntityIDFor("binary_sensor", entry.ID, "doorbell"),
			defaultEntityIDFor("binary_sensor", entry.ID, "call"),
			defaultEntityIDFor("binary_sensor", entry.ID, "access"),
			defaultEntityIDFor("binary_sensor", entry.ID, "tamper"),
		}
	default:
		return nil
	}
}

func intercomCard(entry streams.Entry) map[string]any {
	card := map[string]any{
		"type": "vertical-stack",
		"cards": []map[string]any{
			{
				"type":         "picture-glance",
				"title":        entry.Name,
				"camera_image": defaultEntityIDFor("camera", entry.ID, "camera"),
				"camera_view":  "auto",
				"entities": []string{
					defaultEntityIDFor("binary_sensor", entry.ID, "doorbell"),
					defaultEntityIDFor("binary_sensor", entry.ID, "call"),
					defaultEntityIDFor("binary_sensor", entry.ID, "access"),
				},
			},
			{
				"type":               "entities",
				"title":              "Call Session",
				"show_header_toggle": false,
				"entities": []any{
					map[string]any{"entity": defaultEntityIDFor("sensor", entry.ID, "call_state"), "name": "Call State"},
					map[string]any{"entity": defaultEntityIDFor("sensor", entry.ID, "last_call_source"), "name": "Last Call Source"},
					map[string]any{"entity": defaultEntityIDFor("sensor", entry.ID, "last_ring_at"), "name": "Last Ring At"},
					map[string]any{"entity": defaultEntityIDFor("sensor", entry.ID, "last_call_started_at"), "name": "Call Started"},
					map[string]any{"entity": defaultEntityIDFor("sensor", entry.ID, "last_call_ended_at"), "name": "Call Ended"},
					map[string]any{"entity": defaultEntityIDFor("sensor", entry.ID, "last_call_duration_seconds"), "name": "Call Duration"},
					map[string]any{"entity": defaultEntityIDFor("binary_sensor", entry.ID, "tamper"), "name": "Tamper"},
				},
			},
			intercomActionsCard(entry),
		},
	}
	return card
}

func intercomActionsCard(entry streams.Entry) map[string]any {
	entities := make([]any, 0, 4+entry.LockCount)
	if entry.Intercom != nil && entry.Intercom.SupportsVTOCallAnswer {
		entities = append(entities, map[string]any{
			"entity": defaultEntityIDFor("button", entry.ID, "answer"),
			"name":   "Answer Call",
		})
	}
	entities = append(entities, map[string]any{
		"entity": defaultEntityIDFor("button", entry.ID, "hangup"),
		"name":   "Hang Up Call",
	})
	if entry.Intercom != nil && entry.Intercom.SupportsBridgeSessionReset {
		entities = append(entities, map[string]any{
			"entity": defaultEntityIDFor("button", entry.ID, "intercom_reset"),
			"name":   "Reset Bridge Session",
		})
	}
	if entry.Intercom != nil && entry.Intercom.SupportsExternalAudioExport {
		entities = append(entities,
			map[string]any{
				"entity": defaultEntityIDFor("button", entry.ID, "uplink_enable"),
				"name":   "Enable RTP Export",
			},
			map[string]any{
				"entity": defaultEntityIDFor("button", entry.ID, "uplink_disable"),
				"name":   "Disable RTP Export",
			},
		)
	}
	for index := 0; index < entry.LockCount; index++ {
		lockID := defaultEntityIDFor("button", lockEntityID(entry.ID, index), "open")
		entities = append(entities, map[string]any{
			"entity": lockID,
			"name":   lockButtonName(index),
		})
	}

	title := "Intercom Actions"
	if entry.LockCount <= 0 {
		title = "Call Actions"
	}

	return map[string]any{
		"type":               "entities",
		"title":              title,
		"show_header_toggle": false,
		"entities":           entities,
	}
}

func lockEntityID(rootID string, index int) string {
	return fmt.Sprintf("%s_lock_%02d", rootID, index)
}

func lockButtonName(index int) string {
	if index == 0 {
		return "Open Door"
	}
	return fmt.Sprintf("Open Door %d", index+1)
}
